### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.4 compiler

### ISSUE THREAD

**Issue by gi097** [geosparklabs/geospark-sdk-ios#2]
When trying to use your SDK, I get the following error:

```Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.4 compiler```

This could mean that your compiled framework does not include the `.swiftinterface` files for other compiler versions. One can fix this by setting `BUILD_LIBRARY_FOR_DISTRIBUTION` to `YES` when compiling the framework on your side.

Right now it looks like that I am forced to use the exact same compiler version as this framework was compiled with, which is not ideal. If there's any other method to make it work with the current version of the framework, please let me know. 😄 

Reference: https://stackoverflow.com/a/58656323

Xcode: Version 11.5 (11E608c)
SDK version: 2.2.3

**Comment by jothipriyadharshanr** [comment]
> When trying to use your SDK, I get the following error:
> 
> `Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.4 compiler`
> 
> This could mean that your compiled framework does not include the `.swiftinterface` files for other compiler versions. One can fix this by setting `BUILD_LIBRARY_FOR_DISTRIBUTION` to `YES` when compiling the framework on your side.
> 
> Right now it looks like that I am forced to use the exact same compiler version as this framework was compiled with, which is not ideal. If there's any other method to make it work with the current version of the framework, please let me know. 😄
> 
> Reference: https://stackoverflow.com/a/58656323
> 
> Xcode: Version 11.5 (11E608c)
> SDK version: 2.2.3

The SDK version 2.2.4 is now updated to support the mentioned compiler.
Let us know if you face any issues.

**Comment by gi097** [comment]
Thanks a lot, it works now.
